export const BASE_PATH = '/'
export const NO_MATCH_PATH = '*'

export const PROJECTS_PATH = 'projects'
export const MANAGER_PATH = 'manager'
export const EMPLOYEE_PATH = 'employee'
export const EMPLOYEE_DETAILS_PATH = 'employee/:eId'
export const EVENTS_PATH = 'events'
export const CONTACT_US_PATH = 'contact-us'
export const LOGIN_PATH = 'login'
export const SIGNUP_PATH = 'signup'
export const FORGOT_PASSWORD_PATH = 'forgot'

export const DASHBOARD_PATH = 'dashboard'


export const PROJECTS_LINK = '/projects'
export const MANAGER_LINK = '/manager'
export const EMPLOYEE_LINK = '/employee'
export const EVENTS_LINK = '/events'
export const CONTACT_US_LINK = '/contact-us'
export const LOGIN_LINK= '/login'
export const SIGNUP_LINK = '/signup'
export const FORGOT_PASSWORD_LINK = '/forgot'
export const DASHBOARD_LINK = '/dashboard'